### ISSUE TITLE
Sharing/Creation of a netcdf with the skill metrics (RMSE, ...) of your models.

### ISSUE THREAD

**Issue by ghiggi** [jweyn/DLWP-CS#6]
Hi Jonathan  :)

I am benchmarking my model with previous works (yours, Rasp, ...), and I was wondering if you could share a NetCDF with the global average of the skill metrics (as function of leadtime) you computed for your model(s) and IFS T42, IFS T63 and the S2S ECMWF Control.
It would help to do a proper comparison !
 
Thanks in advance !

**Comment by jweyn** [comment]
Hi @ghiggi,

Sure, I have attached json files of the metrics (ignore the fact that the key is "mse", they are ACC and RMSE metrics as the file name says). However, I recommend exercising caution when directly comparing these, since I computed the metrics on a different grid (1.5 degrees, inverted from a cubed sphere grid) than other models in WeatherBench. For the most fair comparison, it might be best to look at how Stephan computed the score for our model in [that repo](https://github.com/pangeo-data/WeatherBench/blob/master/notebooks/Weyn2020-scores.ipynb).

Jonathan
[metrics.zip](https://github.com/jweyn/DLWP-CS/files/6137677/metrics.zip)
